### ISSUE TITLE
登录模块

### ISSUE THREAD

**Issue by lzh0627** [haopengmai/dianping#2]
利用Redis控制了一分钟不能重复发验证码，如何出现5分钟8次的情况

**Comment by haopengmai** [comment]
用redis的Hash数据结构即可解决

**Comment by haopengmai** [comment]
> 利用Redis控制了一分钟不能重复发验证码，如何出现5分钟8次的情况

用redis的ZSET数据集结构即可解决，key为用户的唯一标识，value设置为 当用户发送验证码的时间戳（score），然后用户每次发送验证码之前，先删除集合中超过 5 分钟的时间戳记录，再用count命令 看看剩下的集合元素是否大于8次即可
